namespace MvkServer.Sound
{
    /// <summary>
    /// Все звуковые семплы
    /// </summary>
    public enum AssetsSample
    {
        None,

        Click,
        Bow,
        Break,

        BucketEmptyLava1,
        BucketEmptyLava2,
        BucketEmptyLava3,
        BucketEmptyWater1,
        BucketEmptyWater2,
        BucketEmptyWater3,
        BucketFillLava1,
        BucketFillLava2,
        BucketFillLava3,
        BucketFillWater1,
        BucketFillWater2,
        BucketFillWater3,

        DamageDrown1,
        DamageDrown2,
        DamageDrown3,
        DamageDrown4,
        DamageFallBig,
        DamageFallSmall,
        DamageFireHurt1,
        DamageFireHurt2,
        DamageFireHurt3,
        DamageHit1,
        DamageHit2,
        DamageHit3,

        DigGlass1,
        DigGlass2,
        DigGlass3,
        DigGrass1,
        DigGrass2,
        DigGrass3,
        DigGrass4,
        DigGravel1,
        DigGravel2,
        DigGravel3,
        DigGravel4,
        DigSand1,
        DigSand2,
        DigSand3,
        DigSand4,
        DigStone1,
        DigStone2,
        DigStone3,
        DigStone4,
        DigWood1,
        DigWood2,
        DigWood3,
        DigWood4,

        DoorClose,
        DoorOpen,

        Drink,
        Eat1,
        Eat2,
        Eat3,

        Explode1,
        Explode2,
        Explode3,
        Explode4,

        Fire,
        FireFizz,
        FireIgnite,

        LiquidSplash1,
        LiquidSplash2,
        LiquidSwim1,
        LiquidSwim2,
        LiquidSwim3,
        LiquidSwim4,

        LiquidLava,
        LiquidLavaPop,
        LiquidWater,

        MobChickenHurt1,
        MobChickenHurt2,
        MobChickenPlop,
        MobChickenSay1,
        MobChickenSay2,
        MobChickenSay3,
        MobChickenStep1,
        MobChickenStep2,

        StepGrass1,
        StepGrass2,
        StepGrass3,
        StepGrass4,
        StepGravel1,
        StepGravel2,
        StepGravel3,
        StepGravel4,
        StepSand1,
        StepSand2,
        StepSand3,
        StepSand4,
        StepStone1,
        StepStone2,
        StepStone3,
        StepStone4,
        StepWood1,
        StepWood2,
        StepWood3,
        StepWood4
        
    }
}
