//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvkAssets {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLanguage() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvkAssets.ResourceLanguage", typeof(ResourceLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на gui.singleplayer:Адзіночная гульня
        ///gui.multiplayer:Сеткавая гульня
        ///gui.options:Налады
        ///gui.exit:Вынахад
        ///gui.exit.world:Выхад са свету
        ///gui.nikname:Імя гульца
        ///gui.fps:FPS
        ///gui.maxfps:Максімум FPS
        ///gui.overview.chunks:Агляд чанкаў
        ///gui.volume.sound:Агульная гучнасць
        ///gui.volume.music:Гучнасць музыкі
        ///gui.volume.off:Выключаны гук
        ///gui.smooth.lighting.on:Плыўнае асвятленне ўключана
        ///gui.smooth.lighting.off:Плыўнае асвятленне выключана
        ///gui.size.interface:Інтэрфейс
        ///gui.apply:Ужыць
        ///gui.cancel:Адмена
        ///gui.no [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Belarusian {
            get {
                return ResourceManager.GetString("Belarusian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на gui.singleplayer:Singleplayer
        ///gui.multiplayer:Multiplayer
        ///gui.options:Options
        ///gui.exit:Quit
        ///gui.nikname:Player name
        ///gui.fps:FPS
        ///gui.maxfps:Maximum FPS
        ///gui.overview.chunks:Chunks overview
        ///gui.volume.sound:Overall volume
        ///gui.volume.music:Music volume
        ///gui.volume.off:Sound off
        ///gui.smooth.lighting.on:Smooth lighting on
        ///gui.smooth.lighting.off:Smooth lighting off
        ///gui.size.interface:Interface
        ///gui.apply:Apply
        ///gui.cancel:Cancel
        ///gui.no:No
        ///gui.yes:Yes
        ///gui.connect:Connect
        ///gui.world.empty:- Empty -
        ///g [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на gui.singleplayer:Одиночная игра
        ///gui.multiplayer:Сетевая игра
        ///gui.options:Настройки
        ///gui.exit:Выход
        ///gui.exit.world:Выход из мира
        ///gui.nikname:Имя игрока
        ///gui.fps:FPS
        ///gui.maxfps:Максимум FPS
        ///gui.overview.chunks:Обзор чанков
        ///gui.volume.sound:Общая громкость
        ///gui.volume.music:Громкость музыки
        ///gui.volume.off:Выключен звук
        ///gui.smooth.lighting.on:Плавное освещение включено
        ///gui.smooth.lighting.off:Плавное освещение выключено
        ///gui.size.interface:Интерфейс
        ///gui.apply:Применить
        ///gui.cancel:Отмена
        ///gui.no:Нет        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
    }
}
